version: '3.8'

services:
  app:
    image: your-image-name
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network