version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/db_username
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - mysql_root_password
      - db_username
      - db_password
      - db_name
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  golang-app:
  build: .
  depends_on:
    - mysql
  secrets:
    - db_username
    - db_password
    - db_address
    - db_name
    - jwt_key
  networks:
    - app-network
  ports:
    - "8080:8080"

secrets:
  mysql_root_password:
    file: /home/debian/.env/secrets/mysql_root_password.txt
  db_username:
    file: /home/debian/.env/secrets/db_username.txt
  db_password:
    file: /home/debian/.env/secrets/db_password.txt
  db_name:
    file: /home/debian/.env/secrets/db_name.txt
  db_address:
    file: /home/debian/.env/secrets/db_address.txt
  jwt_key:
    file: /home/debian/.env/secrets/jwt_key.txt

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
