version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/db_username
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - mysql_root_password
      - db_username
      - db_password
      - db_name
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  golang-app:
    build: .
    secrets:
      - db_username
      - db_password
      - db_address
      - db_name
      - jwt_key
      - gin_mode
    networks:
      - app-network
    ports:
      - "8080:8080"

secrets:
  mysql_root_password:
    external: true
  db_username:
    external: true
  db_password:
    external: true
  db_name:
    external: true
  db_address:
    external: true
  jwt_key:
    external: true
  gin_mode:
    external: true


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
